### ISSUE TITLE
Possible bug in the 2 / 4 ratio

### ISSUE THREAD

**Issue by Nakilon** [eulerscheZahl/2048#1]
https://github.com/eulerscheZahl/2048/blob/ddb54a32cbe6a900c474f2c1ba5812e105711f35/src/main/java/engine/Board.java#L34

I didn't play your implementation but knowing the bug that was in the stolen Android version of the game I decided to dive into the code and... doesn't it spawn 2 and 4 in 50/50 ratio? Shouldn't it be:

```
int value = (seed & 0x11) == 0 ? 4 : 2;
```

?

**Comment by eulerscheZahl** [comment]
Let's bruteforce the answer: https://tech.io/snippet/bfX0xLL
```
2: 499605
4: 500395
```

with your suggested `0x11` it would be:
```
2: 750465
4: 249535
```
The current implementation seems to have a much better distribution than your suggestion. As to be expected with a "full random" number (it's not), each bit should be 1 in 50% of the cases and 0 in the other 50%. You suggest checking 2 bits and both being 0. That's about a 25% chance.
Moreover the value and spawn location are less independent your way: get a 2 here or a 4 somewhere else.


And of course I can't change it now anyways, as some players already put a lot of effort into their solutions.
I don't even know the outcome: either the new validators would allow even higher scores or it would make the current highscores completely impossible.

edit:
I took the random generator from [project euler](https://projecteuler.net/problem=252) in case you wonder.

**Comment by Nakilon** [comment]
Not sure I understood the part about the spawn location but that's the essence of the bug -- supposing that game should spawn 2 and 4 in the same amount. The game is designed to spawn 75% of 2 and 25% of 4. It's working like that in the original implementation and on iOS. Spawning 2 and 4 in the same amount results in much higher scores and essentially wasn't supposed to be like that by the original author of the game.

**Comment by eulerscheZahl** [comment]
Oh, you want a biased spawn? Then I got you wrong.

Regarding the biased spawn: I might had an error in my thinking here. I should do some testing before claiming that but I have a feeling that some tiles might be more likely to spawn a 2 and while others spawn a 4. I'm interested in a realistic gameplay scenario here, which has some cells empty much less often than others.

But as said, the effort of previous players is a killer argument for me not to touch the generator anymore.
